### ISSUE TITLE
Bearing calculations

### ISSUE THREAD

**Issue by JBergsee** [dastrobu/vincenty#16]
Hi!

Nice work on the Vincenty formula! I have added calculations for initial and final bearing. Would you like me to create a PR to add them?

**Comment by dastrobu** [comment]
@JBergsee thanks. I did not require initial and final bearing so far, but calculating them would certainly fit well into this tiny package and a PR would be welcome.

**Comment by JBergsee** [comment]
Good, I just finished.
The changes are quite "invasive", returning a (Double,Double,Double) instead of a scalar Double, so I renamed the function. 
Also complemented the tests.
Should probably edit the readme if you approve the changes, and I haven't changed anything in the package metadata.

**Comment by dastrobu** [comment]
Closed by #17
