### ISSUE TITLE
Assertion failed: x.lat '40.9142' outside [-π/2, π/2]

### ISSUE THREAD

**Issue by houmie** [dastrobu/vincenty#20]
Hello,

I was very excited to use this project. But it seems it's failing.

Vincenty in Python works with these coordinates:

```
Location1 = (50.4513, 12.3602)
Location2 = (40.9142, 29.1479)
vincenty(Location1, Location2)
1676.709865
```

but this project fails with the error: ```Assertion failed: x.lat '40.9142' outside [-π/2, π/2]```
```
do {
            let d = try distance((lat: latUser, lon: lngUser), (lat: latServer, lon: lngServer))
            return d
        } catch let error {
            SwiftyBeaver.error("Distance calculation error: \(error.localizedDescription)")
            return nil
        }
```

Based on the assertion the value is too high, but why is it working in Python?
Thanks

**Comment by dastrobu** [comment]
Because this package uses the SI unto [rad](https://en.wikipedia.org/wiki/Radian) to define angles, whereas other packages may use [degree](https://en.wikipedia.org/wiki/Degree_(angle)). You need to convert your positions from degree to rad, then it should work as expected.

**Comment by houmie** [comment]
Ah yes, I found them in your unit tests.
```
private func rad<T: BinaryFloatingPoint>(fromDegree d: T) -> T {
    return d * T.pi / 180
}

private extension BinaryFloatingPoint {
    /// degree converted to radians
    var asRad: Self {
        return rad(fromDegree: self)
    }
}
```
Now I can use .asRad on the coordinates when passing them in.  That wasn't obvious to be honest. 

Great work! Thanks
